  {
    slug: 'thermocold',
    name: 'Thermocold',
    rubro: 'Servicio técnico y repuestos',
    city: 'Talca',
    tagline: 'La página como orden de trabajo: verde de su letrero, marcas del mostrador en cinta y repuestos reales de su ficha.',
    gradient: 'linear-gradient(135deg, #F4F6F1 0%, #1E7A3E 90%, #0D4524 190%)',
  },
  {
    slug: 'transportes-opazo',
    name: 'Transportes Opazo',
    rubro: 'Transporte de carga',
    city: 'San Javier',
    tagline: 'La página como ficha de ruta: asfalto y azul de su camión, manifiesto de cargas y flota real al frente.',
    gradient: 'linear-gradient(135deg, #10161E 0%, #2E63C4 120%, #F2B705 200%)',
  },
  {
    slug: 'consulta-medica-san-clemente',
    name: 'Consulta Médica San Clemente',
    rubro: 'Kinesiología',
    city: 'San Clemente',
    tagline: 'La página como consulta de barrio: crema y salvia, arco de esquina y sus líneas de atención reales.',
    gradient: 'linear-gradient(135deg, #FAF4EA 0%, #3A7D5C 90%, #25543D 190%)',
  },
  {
    slug: 'centro-tecnologico-de-suelos-y-cultivos',
    name: 'CTSyC',
    rubro: 'Laboratorio de suelos',
    city: 'Talca',
    tagline: 'La página como perfil de suelo: cinco estratos de análisis en los tonos del logo de la U. de Talca, con fotos del laboratorio.',
    gradient: 'linear-gradient(135deg, #F5EFE0 0%, #C9974E 55%, #3E551E 140%)',
  },
  {
    slug: 'cooperativa-riego-del-centro',
    name: 'Riego del Centro',
    rubro: 'Cooperativa de regantes',
    city: 'San Clemente',
    tagline: 'La línea del agua: petróleo de canal y lima de cultivo, hitos desde 1966 y las compuertas del Taco fotografiadas.',
    gradient: 'linear-gradient(135deg, #0C2E3A 0%, #16728A 75%, #A8C622 180%)',
  },
  {
    slug: 'conequip',
    name: 'CONEQUIP',
    rubro: 'Constructora',
    city: 'Talca',
    tagline: 'Portafolio visto desde dron: navy y rojo de obra, índice de servicios numerado y el registro aéreo de sus propias plantas.',
    gradient: 'linear-gradient(135deg, #0A1524 0%, #10203A 60%, #E42620 190%)',
  },