import type { Metadata } from 'next'
import Link from 'next/link'
import { SITE, whatsappLink } from '@/lib/config'
import { DEMOS } from './data'
import DemoCatalog from './catalog'

// Mockups personalizados para leads reales (carpeta propia en /demos).
const BLITZ = [
  {
    slug: 'la-surena-de-molina',
    name: 'La Sureña de Molina',
    rubro: 'Restaurante de comida casera',
    city: 'Molina',
    tagline: 'Letrero de ruta: rojo de la fachada, crema y postales de la cocina casera.',
    gradient: 'linear-gradient(135deg, #F6EEDF 0%, #F3DAD2 55%, #B23A2A 140%)',
  },
  {
    slug: 'kevin-celedon-psicologo-talca',
    name: 'Kevin Celedón | Psicólogo',
    rubro: 'Psicólogo',
    city: 'Talca',
    tagline: 'Espacio seguro: teal del logo, pizarra de la consulta y calma editorial.',
    gradient: 'linear-gradient(135deg, #F5F2EA 0%, #DDF0ED 55%, #0FA394 140%)',
  },
  {
    slug: 'clinica-veterinaria-ecovets',
    name: 'Clínica Veterinaria Ecovets',
    rubro: 'Clínica veterinaria',
    city: 'Rancagua',
    tagline: 'Guardia 24/7: ciruela de noche, rosa del logo y monitor de pulso.',
    gradient: 'linear-gradient(135deg, #17080F 0%, #301526 55%, #F2437F 140%)',
  },
  {
    slug: 'constructora-musalem',
    name: 'Constructora Musalem',
    rubro: 'Constructora',
    city: 'Concepción',
    tagline: 'Lámina de obra: papel milimetrado, tinta azul plano y sello amarillo.',
    gradient: 'linear-gradient(135deg, #EDF1F6 0%, #B7C9DC 55%, #1D4E89 140%)',
  },
  {
    slug: 'taller-ferrasil',
    name: 'Taller Ferrasil',
    rubro: 'Taller mecánico',
    city: 'Concepción',
    tagline: 'Garaje de noche: carbón, amarillo seguridad y muro de reseñas reales.',
    gradient: 'linear-gradient(135deg, #141518 0%, #2A2D33 55%, #F2C200 140%)',
  },
  {
    slug: 'clinica-veterinaria-zoovet',
    name: 'Clínica Veterinaria Zoovet',
    rubro: 'Clínica veterinaria',
    city: 'Talca',
    tagline: 'Carnet de paciente: crema papel, verde clínico y terracota, con fichas y sello de pata.',
    gradient: 'linear-gradient(135deg, #1C4433 0%, #2E6B4F 55%, #B04A2A 140%)',
  },
  {
    slug: 'lubricentro-huamachuco',
    name: 'Lubricentro Huamachuco',
    rubro: 'Lubricentro y accesorios',
    city: 'San Clemente',
    tagline: 'Cambio de aceite y accesorios: navy, rojo y dorado aceite.',
    gradient: 'linear-gradient(135deg, #0E1C29 0%, #12283C 55%, #B3301C 140%)',
  },
  {
    slug: 'taller-zunino-266',
    name: 'Taller Zunino 266',
    rubro: 'Taller mecánico',
    city: 'San Clemente',
    tagline: 'Mecánica y scanner a domicilio: carbón y naranja industrial.',
    gradient: 'linear-gradient(135deg, #141519 0%, #3A404C 55%, #B0440D 140%)',
  },
  {
    slug: 'antumalen-restaurant',
    name: 'Antümalen Restaurant',
    rubro: 'Restaurant y comida casera',
    city: 'San Clemente',
    tagline: 'Comida casera en Ruta 115: mostaza, terracota y crema.',
    gradient: 'linear-gradient(135deg, #231508 0%, #B8441D 55%, #E3A008 140%)',
  },
  {
    slug: 'lavaseco-flash',
    name: 'Lavaseco Flash',
    rubro: 'Lavandería y lavaseco',
    city: 'Talca',
    tagline: 'Lavandería doméstica e industrial con tres sucursales.',
    gradient: 'linear-gradient(135deg, #102A36 0%, #146B66 55%, #F5B642 140%)',
  },
  {
    slug: 'delicias-caseras-fabiana',
    name: 'Delicias Caseras Fabiana',
    rubro: 'Panadería y pastelería',
    city: 'San Clemente',
    tagline: 'Preparaciones caseras para compartir.',
    gradient: 'linear-gradient(135deg, #55291F 0%, #A34127 55%, #E5BC84 140%)',
  },
  {
    slug: 'marbella-talcahuano',
    name: 'Café Marbella',
    rubro: 'Café y pastelería',
    city: 'Talcahuano',
    tagline: 'El café clásico del puerto: espresso, caramelo y vitrina de tortas.',
    gradient: 'linear-gradient(135deg, #2A1B10 0%, #7C2E3E 55%, #E8C893 140%)',
  },
  {
    slug: 'sabor-marino-talcahuano',
    name: 'Restaurante Sabor Marino',
    rubro: 'Marisquería',
    city: 'Talcahuano',
    tagline: 'La picada de mariscos de Manuel Rodríguez: paila marina y pescado a lo pobre.',
    gradient: 'linear-gradient(135deg, #08202E 0%, #0E2F42 55%, #E4572E 140%)',
  },
  {
    slug: 'puntanorte-puerto',
    name: 'PuntaNorte Puerto',
    rubro: 'Restaurant de mariscos',
    city: 'Talcahuano',
    tagline: 'Mariscos frente al puerto y noches de karaoke hasta las 3 AM.',
    gradient: 'linear-gradient(135deg, #0F2422 0%, #16302E 55%, #C9A05C 140%)',
  },
  {
    slug: 'brilla-el-sol-talca',
    name: 'Complejo Deportivo Brilla El Sol',
    rubro: 'Campo de fútbol',
    city: 'Talca',
    tagline: 'Cancha sintética con focos en 12 Sur: arrienda por bloques de 90 minutos.',
    gradient: 'linear-gradient(135deg, #10392E 0%, #178553 55%, #F4C64E 140%)',
  },
  {
    slug: 'complejo-deportivo-carlos-aravena-se',
    name: 'Complejo Deportivo Carlos Aravena',
    rubro: 'Centro deportivo',
    city: 'Talca',
    tagline: 'Piscina, cancha sintética y parque del SERVIU en la 12 Oriente.',
    gradient: 'linear-gradient(135deg, #14181B 0%, #075E7D 60%, #7FC4DC 140%)',
  },
  {
    slug: 'contador-auditor-talca-jacqueline-mo',
    name: 'JMM · Contador Auditor',
    rubro: 'Contable',
    city: 'Talca',
    tagline: 'Contabilidad, tributario y laboral para pymes, en 1 Sur 865.',
    gradient: 'linear-gradient(135deg, #18161B 0%, #8A6530 70%, #E9D9B8 140%)',
  },
  {
    slug: 'pannton-arquitectura',
    name: 'Pannton, Arquitectura y Soluciones Gráficas',
    rubro: 'Impresión y diseño',
    city: 'Talca',
    tagline: 'Taller de impresión en Lomas de Lircay: grafito, papel y ámbar.',
    gradient: 'linear-gradient(135deg, #1C1B19 0%, #E0A21B 140%)',
  },
  {
    slug: 'gacitua-producciones',
    name: 'Gacitúa Producciones',
    rubro: 'Eventos y banquetería',
    city: 'Talca',
    tagline: 'Eventos y arriendo de vajilla en Villa Colín Sur: verde profundo y dorado.',
    gradient: 'linear-gradient(135deg, #1F3A2E 0%, #B8893A 140%)',
  },
  {
    slug: 'villa-antillanca-hotel-centro-eventos',
    name: 'Villa Antillanca, Hotel & Centro de Eventos',
    rubro: 'Hotel y eventos',
    city: 'Talca',
    tagline: 'Hospedaje, piscina y celebraciones camino a San Clemente.',
    gradient: 'linear-gradient(135deg, #0C211A 0%, #527A68 55%, #C38A3A 140%)',
  },
  {
    slug: 'automotriz-tudela-mecanica-electricidad',
    name: 'Automotriz Tudela',
    rubro: 'Mecánica y electricidad',
    city: 'Talca',
    tagline: 'Taller automotriz de barrio: mecánica, electricidad y diagnóstico.',
    gradient: 'linear-gradient(135deg, #111517 0%, #39434A 55%, #F0782B 140%)',
  },
  {
    slug: 'hope-bakery-chile',
    name: 'Hope Bakery Chile',
    rubro: 'Panadería y pastelería',
    city: 'Talca',
    tagline: 'Artesanal y cálido: masa madre, horno y vitrina de pastelería.',
    gradient: 'linear-gradient(135deg, #4A2518 0%, #A74728 55%, #F2C879 140%)',
  },
  {
    slug: 'monky-coffee',
    name: 'Monky Coffee',
    rubro: 'Cafetería',
    city: 'Talca',
    tagline: 'Café de especialidad, métodos y conversación en 1 Oriente.',
    gradient: 'linear-gradient(135deg, #0D241D 0%, #16352B 55%, #D5A441 140%)',
  },
  {
    slug: 'gotitas-de-amor',
    name: 'Sala Cuna y Jardín Infantil Gotitas de Amor',
    rubro: 'Educación inicial',
    city: 'Talca',
    tagline: 'Cálido y cercano: educación inicial, gotas, hojas y sol.',
    gradient: 'linear-gradient(135deg, #173B36 0%, #5D9A73 55%, #F6C76C 140%)',
  },
  {
    slug: 'new-era-barbershop',
    name: 'New Era Barbershop',
    rubro: 'Barbería',
    city: 'Talca',
    tagline: 'Cartel de barbería directo: negro, naranja y amarillo, con agenda por WhatsApp.',
    gradient: 'linear-gradient(135deg, #111315 0%, #E4572E 55%, #E6B84F 140%)',
  },
  {
    slug: 'triadent',
    name: 'Clínica Dental Triadent',
    rubro: 'Clínica dental',
    city: 'Talca',
    tagline: 'Clínico premium y luminoso: menta y azul profundo.',
    gradient: 'linear-gradient(135deg, #0F3B57 0%, #1D9E8E 140%)',
  },
  {
    slug: 'centro-m-dico-veterinario-one-health',
    name: 'One Health',
    rubro: 'Centro veterinario',
    city: 'Maule',
    tagline: 'Amable y moderno: salvia, durazno y crema.',
    gradient: 'linear-gradient(135deg, #4E6B50 0%, #F2B48C 140%)',
  },
  {
    slug: 'homyvet',
    name: 'Clínica Veterinaria Homyvet',
    rubro: 'Clínica veterinaria',
    city: 'Talca',
    tagline: 'Hogar y cuidado: mostaza, azul marino y hueso.',
    gradient: 'linear-gradient(135deg, #1E2C4E 0%, #D9A02B 140%)',
  },
  {
    slug: 'altos-de-lircay',
    name: 'Altos de Lircay',
    rubro: 'Clínica dental',
    city: 'San Clemente',
    tagline: 'Cercano y natural: verde bosque y cobre.',
    gradient: 'linear-gradient(135deg, #16342A 0%, #B4643C 140%)',
  },
  {
    slug: 'jd-abogados',
    name: 'J&D Abogados',
    rubro: 'Estudio jurídico',
    city: 'Talca',
    tagline: 'Serio y elegante: grafito y dorado apagado.',
    gradient: 'linear-gradient(135deg, #1B1E22 0%, #A5885A 140%)',
  },
  {
    slug: 'santa-fe',
    name: 'Ingeniería y Construcciones Santa Fe',
    rubro: 'Constructora',
    city: 'Talca',
    tagline: 'Industrial sólido: acero y naranjo de seguridad.',
    gradient: 'linear-gradient(135deg, #16191D 0%, #E8631A 140%)',
  },
  {
    slug: 'rancho-itahue',
    name: 'Rancho Itahue',
    rubro: 'Agroturismo y eventos',
    city: 'Molina',
    tagline: 'Editorial de campo: verde bosque, hueso y ámbar, con fotos.',
    gradient: 'linear-gradient(135deg, #12231A 0%, #B97E33 140%)',
  },
  {
    slug: 'panaderia-bravo',
    name: 'Panadería Bravo',
    rubro: 'Panadería y pastelería',
    city: 'Molina',
    tagline: 'Pan de verdad: crema de masa, chocolate y dorado de horno.',
    gradient: 'linear-gradient(135deg, #2E1C0E 0%, #D59A33 140%)',
  },
  {
    slug: 'vivero-dona-ines',
    name: 'Vivero Doña Inés',
    rubro: 'Vivero y plantas',
    city: 'Molina',
    tagline: 'El vivero de siempre: verde hoja, terracota y crema, con fotos.',
    gradient: 'linear-gradient(135deg, #24381F 0%, #C1663F 140%)',
  },
  {
    slug: 'vivero-entre-raices',
    name: 'Vivero Entre Raices',
    rubro: 'Centro de jardinería',
    city: 'Linares',
    tagline: 'Periódico clásico: azul petróleo, blanco roto y menta, con fotos.',
    gradient: 'linear-gradient(135deg, #093540 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'barberia-rulos-style-barberia-curico',
    name: 'Barbería Rulos Style',
    rubro: 'Barbería',
    city: 'Curicó',
    tagline: 'Bento industrial y directo: naranja construcción, hormigón y arena, con fotos.',
    gradient: 'linear-gradient(135deg, #26292D 0%, #E4572E 140%)',
  },
  {
    slug: 'lua-nails',
    name: 'Lua Nails Home',
    rubro: 'Manicure y uñas',
    city: 'Talca',
    tagline: 'Delicado y premium: rosa empolvado, berenjena y dorado suave.',
    gradient: 'linear-gradient(135deg, #4A1F33 0%, #C9A227 140%)',
  },
  {
    slug: 'nailsyus',
    name: 'NAILSYUS',
    rubro: 'Salón de manicura y pedicura',
    city: 'Talca',
    tagline: 'Cuadrícula suiza: naranja construcción, hormigón y arena, cartel moderno con fotos.',
    gradient: 'linear-gradient(135deg, #3A3F44 0%, #E4572E 140%)',
  },
  {
    slug: 'wow-park',
    name: 'Wow Park Talca',
    rubro: 'Parque infantil y cumpleaños',
    city: 'Talca',
    tagline: 'Juguetón y familiar: azul confiable, amarillo festivo y coral.',
    gradient: 'linear-gradient(135deg, #0E2F5E 0%, #1E6FD9 55%, #FF6B4A 140%)',
  },
  {
    slug: 'matrokin',
    name: 'Matrokin SPA',
    rubro: 'Spa y terapias',
    city: 'Molina',
    tagline: 'Calmo y natural: verde salvia, arena y carbón.',
    gradient: 'linear-gradient(135deg, #2B2B27 0%, #7C8F7B 140%)',
  },
  {
    slug: 'sigel',
    name: 'Eléctrico Domiciliario Sigel',
    rubro: 'Electricista a domicilio',
    city: 'Talca',
    tagline: 'Técnico y directo: azul eléctrico, grafito y amarillo de seguridad.',
    gradient: 'linear-gradient(135deg, #15171C 0%, #1B4DFF 140%)',
  },
  {
    slug: 'zamono',
    name: 'Lubricentro Zamono',
    rubro: 'Lavado y lubricentro',
    city: 'Molina',
    tagline: 'Limpio y rápido: azul agua, grafito y blanco.',
    gradient: 'linear-gradient(135deg, #1C1F22 0%, #00A6C4 140%)',
  },
  {
    slug: 'lubricentro-y-repuestos-san-martin',
    name: 'Lubricentro y repuestos San Martín',
    rubro: 'Lubricentro y repuestos',
    city: 'Molina',
    tagline: 'Identidad de taller: grafito, hueso y amarillo aceite.',
    gradient: 'linear-gradient(135deg, #191D1F 0%, #586064 55%, #F2AE38 140%)',
  },
  {
    slug: 'salon-de-belleza-gabriela-saavedra-talca',
    name: 'Salón de Belleza Gabriela Saavedra',
    rubro: 'Centro de estética',
    city: 'Talca',
    tagline: 'Sobrio y de confianza: verde bosque, crema y latón, en bloques partidos.',
    gradient: 'linear-gradient(135deg, #1E3D2F 0%, #C8A24B 140%)',
  },
  {
    slug: 'centro-spa-roxana',
    name: 'Centro Spa Roxana',
    rubro: 'Centro de estética',
    city: 'Curicó',
    tagline: 'Editorial de revista: petróleo, menta y blanco roto, con fotos.',
    gradient: 'linear-gradient(135deg, #0A3742 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'clinica-y-farmacia-veterinaria-angel-guardian',
    name: 'Clínica y Farmacia Veterinaria Ángel Guardián',
    rubro: 'Clínica y farmacia veterinaria',
    city: 'Linares',
    tagline: 'Inmersivo y cálido: vino, hueso y oro viejo, con fotos a sangre.',
    gradient: 'linear-gradient(135deg, #4A1A26 0%, #B98B4E 140%)',
  },
  {
    slug: 'las-viejas-cochinas',
    name: 'Las Viejas Cochinas',
    rubro: 'Restaurante',
    city: 'Talca',
    tagline: 'Panel de datos cumplidor: rojo, gris flota y naranja señal, con fotos.',
    gradient: 'linear-gradient(135deg, #4A4E52 0%, #C1272D 140%)',
  },
  {
    slug: 'la-pica-de-los-tatas',
    name: 'La Picá De Los Tatas',
    rubro: 'Restaurante',
    city: 'Molina',
    tagline: 'Oscuro premium y hospitalario: azul noche, arena y terracota, con vidrio y fotos.',
    gradient: 'linear-gradient(135deg, #0F141C 0%, #1B2A41 55%, #C1663F 140%)',
  },
  {
    slug: 'la-pica-del-mateo',
    name: 'La Pica del Mateo',
    rubro: 'Restaurante familiar',
    city: 'San Clemente',
    tagline: 'Tarjetas apiladas por volumen: azul distribución, gris acero y cian, con fotos.',
    gradient: 'linear-gradient(135deg, #123547 0%, #1F5673 55%, #3CC4DC 140%)',
  },
  {
    slug: 'cafe-la-francesa',
    name: 'Café La Francesa',
    rubro: 'Cafetería',
    city: 'Linares',
    tagline: 'Collage artesanal: verde campo, tierra y crema de papel, con fotos.',
    gradient: 'linear-gradient(135deg, #27361F 0%, #4C6B3C 55%, #8C6239 140%)',
  },
  {
    slug: 'csf-especialidades-veterinarias-san-francisco',
    name: 'CSF Especialidades Veterinarias',
    rubro: 'Clínica veterinaria',
    city: 'Talca',
    tagline: 'Brutalista industrial: azul eléctrico, lima y negro, retícula de obra con fotos.',
    gradient: 'linear-gradient(135deg, #0E0E0E 0%, #2251FF 55%, #C6F24E 140%)',
  },
  {
    slug: 'emporio-vintage-cafe',
    name: 'Emporio Vintage Café',
    rubro: 'Cafetería',
    city: 'Talca',
    tagline: 'Carta tipográfica de cafetería: verde emporio, crema y ámbar, con puntos guía.',
    gradient: 'linear-gradient(135deg, #173E32 0%, #2A7F62 55%, #E8A33D 140%)',
  },
  {
    slug: 'plantitas-ya-vivero-romeral-ventas-de-plantas-y-',
    name: 'Plantitas Yá! & Vivero Romeral',
    rubro: 'Vivero y venta de plantas',
    city: 'Romeral',
    tagline: 'Directorio funcional: azul petróleo, menta y blanco roto, con fotos.',
    gradient: 'linear-gradient(135deg, #093341 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'wake-up',
    name: 'Wake Up',
    rubro: 'Cafetería',
    city: 'Curicó',
    tagline: 'Mosaico fotográfico de catálogo: azul distribución, gris y cian, con fotos.',
    gradient: 'linear-gradient(135deg, #123347 0%, #1F5673 55%, #2FB8D6 140%)',
  },
  {
    slug: 'distribuidora-mym-curico',
    name: 'Distribuidora MyM Curicó',
    rubro: 'Tienda de artículos para el hogar',
    city: 'Curicó',
    tagline: 'Tipográfico industrial: hormigón, naranja construcción y arena, con fotos.',
    gradient: 'linear-gradient(135deg, #3A3F44 0%, #E4572E 140%)',
  },
  {
    slug: 'parrilladas-caupolican',
    name: 'Parrilladas Caupolican',
    rubro: 'Restaurante',
    city: 'Pencahue',
    tagline: 'Ficha utilitaria de carretera: mostaza, verde oscuro y madera, historia por pasos.',
    gradient: 'linear-gradient(135deg, #1B2E24 0%, #D9A441 140%)',
  },
  {
    slug: 'patagonia-dulce-pasteleria',
    name: 'Patagonia dulce pastelería',
    rubro: 'Pastelería',
    city: 'San Clemente',
    tagline: 'Portada de revista pastelera: petróleo, menta y blanco roto, con foto a sangre.',
    gradient: 'linear-gradient(135deg, #093540 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'centro-san-ricardo',
    name: 'Centro San Ricardo',
    rubro: 'Piscina cubierta',
    city: 'San Rafael',
    tagline: 'Línea de tiempo educativa: azul pizarra y amarillo lápiz, con fotos.',
    gradient: 'linear-gradient(135deg, #22353F 0%, #2F4858 55%, #F2B705 140%)',
  },
  {
    slug: 'my-fusion-gym',
    name: 'MY Fusion Gym',
    rubro: 'Gimnasio',
    city: 'Curicó',
    tagline: 'Sobrio y patrimonial: verde bosque, crema y latón, fichas apiladas al hacer scroll.',
    gradient: 'linear-gradient(135deg, #142A20 0%, #1E3D2F 55%, #C8A24B 140%)',
  },
  {
    slug: 'nativa-curico',
    name: 'Nativa Curicó',
    rubro: 'Centro de estética',
    city: 'Curicó',
    tagline: 'Neón nocturno: tinta vino, hueso y oro viejo con glow, marquesina y carta de precios.',
    gradient: 'linear-gradient(135deg, #150A0F 0%, #6B2737 55%, #B98B4E 140%)',
  },
  {
    slug: 'restobar-los-leones',
    name: 'Restobar Los Leones',
    rubro: 'Restobar',
    city: 'Pelarco',
    tagline: 'Editorial de revista: azul eléctrico, lima y titulares gigantes en grilla de 12 columnas.',
    gradient: 'linear-gradient(135deg, #141518 0%, #2251FF 55%, #C6F24E 140%)',
  },
  {
    slug: 'clinica-veterinaria-docpino',
    name: 'Clínica Veterinaria Docpino',
    rubro: 'Clínica veterinaria',
    city: 'Linares',
    tagline: 'Sobrio y patrimonial: verde bosque, crema y latón, doble columna con sidebar pegajoso.',
    gradient: 'linear-gradient(135deg, #142A20 0%, #1E3D2F 55%, #C8A24B 140%)',
  },
  {
    slug: 'girls-house-estetica',
    name: 'Girls House Estética',
    rubro: 'Centro de estética',
    city: 'Molina',
    tagline: 'Catálogo de taller: negro, amarillo señal y acero, vitrina con filtros y precios.',
    gradient: 'linear-gradient(135deg, #17181A 0%, #8A9199 55%, #FFC300 140%)',
  },
  {
    slug: 'vasquez-muebles-linares-spa',
    name: 'Vasquez Muebles Linares',
    rubro: 'Fábrica de muebles',
    city: 'Linares',
    tagline: 'Jardín botánico de taller: azul noche, arena y terracota, arcos y hojas, con fotos.',
    gradient: 'linear-gradient(135deg, #1B2A41 0%, #1B2A41 55%, #C1663F 140%)',
  },
  {
    slug: 'restaurant-el-encuentro',
    name: 'Restaurant El Encuentro',
    rubro: 'Restaurante',
    city: 'Pencahue',
    tagline: 'Cuadrícula suiza utilitaria: mostaza, verde oscuro y hueso, reglas finas y tipografía de cartel.',
    gradient: 'linear-gradient(135deg, #17231C 0%, #2E4A3C 55%, #D9A441 140%)',
  },
  {
    slug: 'muebleria-comercial-sofia',
    name: 'Mueblería Comercial Sofia',
    rubro: 'Fábrica de muebles',
    city: 'Talca',
    tagline: 'Bento modular de taller: verde campo, tierra y crema, con fotos.',
    gradient: 'linear-gradient(135deg, #2C3F22 0%, #4C6B3C 55%, #8C6239 140%)',
  },
  {
    slug: 'clinica-t-renova-spa',
    name: 'Clínica T-Renova SPA',
    rubro: 'Tienda de belleza y salud',
    city: 'Linares',
    tagline: 'Clínico y luminoso: azul petróleo, menta y blanco roto, línea de tiempo horizontal con fotos.',
    gradient: 'linear-gradient(135deg, #093540 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'victoria-nail-school',
    name: 'Victoria Nail School',
    rubro: 'Salón de manicura y pedicura',
    city: 'Pencahue',
    tagline: 'Split-screen logístico: rojo, gris flota y naranja señal, con fotos.',
    gradient: 'linear-gradient(135deg, #C1272D 0%, #4A4E52 55%, #E8631A 140%)',
  },
  {
    slug: 'clinica-dental-bilbao-urgencias-dentales-curico-',
    name: 'Clínica Dental Bilbao',
    rubro: 'Dentista y urgencias 24/7',
    city: 'Curicó',
    tagline: 'Panel de datos patrimonial: verde bosque, crema y latón, tabla de prestaciones con fotos.',
    gradient: 'linear-gradient(135deg, #132A1F 0%, #1E3D2F 55%, #C8A24B 140%)',
  },
  {
    slug: 'ferreteria-williams-pencahue',
    name: 'Ferreteria Williams Pencahue',
    rubro: 'Ferretería y maderas',
    city: 'Pencahue',
    tagline: 'Mosaico fotográfico de mesón: vino, hueso y oro viejo, con fotos.',
    gradient: 'linear-gradient(135deg, #3A1520 0%, #6B2737 55%, #B98B4E 140%)',
  },
  {
    slug: 'taller-mecanico-servimac',
    name: 'Taller Mecánico Servimac',
    rubro: 'Taller de reparación de automóviles',
    city: 'Molina',
    tagline: 'Órdenes de trabajo apiladas al hacer scroll: rojo, gris flota y naranja señal, con fotos.',
    gradient: 'linear-gradient(135deg, #4A4E52 0%, #C1272D 55%, #E8631A 140%)',
  },
  {
    slug: 'hospital-clinico-veterinario-la-granja-linares',
    name: 'Hospital Veterinario La Granja',
    rubro: 'Hospital clínico veterinario',
    city: 'Linares',
    tagline: 'Gaceta veterinaria enérgica: azul eléctrico, lima y titulares de diario, con fotos.',
    gradient: 'linear-gradient(135deg, #0C1B63 0%, #2251FF 55%, #C6F24E 140%)',
  },
  {
    slug: 'nicolas-atelier',
    name: 'Nicolás Atelier',
    rubro: 'Peluquería',
    city: 'Linares',
    tagline: 'Diagonales dinámicas: verde campo, tierra y crema, cortes en ángulo y fotos inclinadas.',
    gradient: 'linear-gradient(135deg, #2E4224 0%, #4C6B3C 55%, #8C6239 140%)',
  },
  {
    slug: 'ultrasport19',
    name: 'Ultrasport19',
    rubro: 'Gimnasio',
    city: 'Pencahue',
    tagline: 'Brutalista industrial: azul pizarra, amarillo lápiz y retícula de obra, con fotos.',
    gradient: 'linear-gradient(135deg, #22303A 0%, #2F4858 55%, #F2B705 140%)',
  },
  {
    slug: 'atlantix-clinica-odontologica-san-javier-de-lonc',
    name: 'Atlantix Clínica Odontológica',
    rubro: 'Clínica dental',
    city: 'San Javier de Loncomilla',
    tagline: 'Hero tipográfico sin foto: azul noche, arena y terracota, calmo y hospitalario.',
    gradient: 'linear-gradient(135deg, #1B2A41 0%, #1B2A41 55%, #C1663F 140%)',
  },
  {
    slug: 'peluqueria-fran-wartemberg',
    name: 'Peluquería Fran Wartemberg',
    rubro: 'Peluquería',
    city: 'Curicó',
    tagline: 'Directorio funcional de taller: negro, amarillo señal y acero, carta de precios con fotos.',
    gradient: 'linear-gradient(135deg, #17181A 0%, #8A9199 55%, #FFC300 140%)',
  },
  {
    slug: 'hostal-josefa',
    name: 'Hostal Josefa',
    rubro: 'Hostal y hospedaje',
    city: 'Curicó',
    tagline: 'Historia por pasos industrial: naranja construcción, hormigón y arena, con fotos.',
    gradient: 'linear-gradient(135deg, #3A3F44 0%, #E4572E 140%)',
  },
  {
    slug: 'brutal-curico',
    name: 'Brutal Curicó',
    rubro: 'Gimnasio',
    city: 'Curicó',
    tagline: 'Bento modular ferretero: mostaza, verde oscuro y madera, con fotos.',
    gradient: 'linear-gradient(135deg, #1D2F26 0%, #2E4A3C 55%, #D9A441 140%)',
  },
  {
    slug: 'comercial-rio-claro',
    name: 'Comercial Río Claro',
    rubro: 'Mayorista de artículos para la higiene',
    city: 'Talca',
    tagline: 'Vitrina de almacén patrimonial: verde bosque, crema y latón, catálogo con filtros y precios.',
    gradient: 'linear-gradient(135deg, #132318 0%, #1E3D2F 55%, #C8A24B 140%)',
  },
  {
    slug: 'le-petit-pasteleria',
    name: 'Le Petit Pasteleria',
    rubro: 'Pastelería',
    city: 'Talca',
    tagline: 'Editorial de revista: azul pizarra, amarillo lápiz y titulares serif gigantes.',
    gradient: 'linear-gradient(135deg, #22353F 0%, #2F4858 55%, #F2B705 140%)',
  },
  {
    slug: 'tienda-by-joseline-spa',
    name: 'Tienda By Joseline Spa',
    rubro: 'Tienda de lencería',
    city: 'Pencahue',
    tagline: 'Minimal de lujo: blanco, líneas de 1px, rojo logística y dorado discreto, con fotos.',
    gradient: 'linear-gradient(135deg, #4A4E52 0%, #C1272D 55%, #E8631A 140%)',
  },
  {
    slug: 'danybloom',
    name: 'danybloom',
    rubro: 'Salón de manicura y pedicura',
    city: 'Talca',
    tagline: 'Split-screen de taller: negro, amarillo señal y acero, bloques alternados con fotos.',
    gradient: 'linear-gradient(135deg, #17181A 0%, #8A9199 55%, #FFC300 140%)',
  },
  {
    slug: 'mia-centro-de-estetica',
    name: 'Mía Centro De Estética',
    rubro: 'Centro de estética',
    city: 'Curicó',
    tagline: 'Doble columna con sidebar pegajoso: verde campo, tierra y crema, con fotos.',
    gradient: 'linear-gradient(135deg, #2E4224 0%, #4C6B3C 55%, #8C6239 140%)',
  },
  {
    slug: 'muebleria-infinity-muebles-talca',
    name: 'Infinity Muebles',
    rubro: 'Carpintería y mueblería',
    city: 'Talca',
    tagline: 'Diagonales dinámicas: naranja construcción, hormigón y arena, cortes en ángulo y fotos inclinadas.',
    gradient: 'linear-gradient(135deg, #3A3F44 0%, #3A3F44 55%, #E4572E 140%)',
  },
  {
    slug: 'hair-home-studio-claudia-beltran',
    name: 'Hair Home studio Claudia Beltrán',
    rubro: 'Centro de estética',
    city: 'Linares',
    tagline: 'Collage artesanal utilitario: mostaza, verde oscuro y papel, tarjetas con cinta adhesiva.',
    gradient: 'linear-gradient(135deg, #1F3229 0%, #2E4A3C 55%, #D9A441 140%)',
  },
  {
    slug: 'cabanas-vista-hermosa',
    name: 'Cabañas Vista Hermosa',
    rubro: 'Cabañas y hospedaje',
    city: 'Río Claro',
    tagline: 'Retro de almacén de barrio: petróleo, menta y blanco roto, sellos y boleta con fotos.',
    gradient: 'linear-gradient(135deg, #093540 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'forastero-sabor-en-cada-bocado',
    name: 'FORASTERO sabor en cada bocado',
    rubro: 'Restaurante',
    city: 'Pencahue',
    tagline: 'Neón nocturno de ruta: azul distribución, gris y cian con glow, letrero luminoso y fichas de cocina.',
    gradient: 'linear-gradient(135deg, #060D15 0%, #1F5673 55%, #3CD9EC 140%)',
  },
  {
    slug: 'damianstyle',
    name: 'DamianStyle',
    rubro: 'Barbería',
    city: 'Pelarco',
    tagline: 'Jardín botánico: vino, hueso y oro viejo, arcos y hojas con luz cálida, con fotos.',
    gradient: 'linear-gradient(135deg, #441722 0%, #6B2737 55%, #B98B4E 140%)',
  },
  {
    slug: 'italo-vet-linares',
    name: 'Italo Vet Linares',
    rubro: 'Veterinario',
    city: 'Linares',
    tagline: 'Historia por pasos: línea de tiempo vertical 01-04 en azul eléctrico y lima, con fotos.',
    gradient: 'linear-gradient(135deg, #0B1E6B 0%, #2251FF 55%, #C6F24E 140%)',
  },
  {
    slug: 'ferreteria-la-ruta',
    name: 'Ferretería La Ruta',
    rubro: 'Tienda de herramientas',
    city: 'Pencahue',
    tagline: 'Carta tipográfica de mostrador: azul eléctrico, lima y puntos guía, con fotos.',
    gradient: 'linear-gradient(135deg, #0A1A5C 0%, #2251FF 55%, #C6F24E 140%)',
  },
  {
    slug: 'bravosgym',
    name: 'Bravosgym',
    rubro: 'Gimnasio',
    city: 'Molina',
    tagline: 'Foto a sangre inmersiva: azul noche, arena y terracota, parallax sutil y casi sin cromo.',
    gradient: 'linear-gradient(135deg, #101A29 0%, #1B2A41 55%, #C1663F 140%)',
  },
  {
    slug: 'gimnasio-body-fitness-talca',
    name: 'Gimnasio Body Fitness Talca',
    rubro: 'Gimnasio',
    city: 'Talca',
    tagline: 'Sala de entrenamiento con máquinas y pesas, en tonos grafito y lima.',
    gradient: 'linear-gradient(135deg, #111916 0%, #26382D 55%, #D2F36B 140%)',
  },
  {
    slug: 'ferreteria-valdebenito',
    name: 'Ferretería Valdebenito',
    rubro: 'Tienda de herramientas',
    city: 'Linares',
    tagline: 'Oscuro premium mayorista: carbón, vidrio y cian con glow, surtido por pasillo y precio por volumen.',
    gradient: 'linear-gradient(135deg, #0A0D12 0%, #1F5673 60%, #45D5E8 140%)',
  },
  {
    slug: 'peluqueria-gloria',
    name: 'Peluquería Gloria',
    rubro: 'Peluquería',
    city: 'Río Claro',
    tagline: 'Carta tipográfica de campo: verde campo, tierra y crema, servicios con puntos guía y foto a sangre.',
    gradient: 'linear-gradient(135deg, #2F4226 0%, #4C6B3C 55%, #8C6239 140%)',
  },
  {
    slug: 'servicio-tecnico-automotriz-millycar',
    name: 'Servicio Técnico Automotriz Millycar',
    rubro: 'Taller mecánico',
    city: 'Curicó',
    tagline: 'Manual del taller: azul pizarra y amarillo lápiz, doble columna con sidebar pegajoso y fotos.',
    gradient: 'linear-gradient(135deg, #22353F 0%, #2F4858 55%, #F2B705 140%)',
  },
  {
    slug: 'mym-taller-mecanico-talca',
    name: 'MyM Taller mecánico y mecánica a domicilio',
    rubro: 'Taller mecánico',
    city: 'Talca',
    tagline: 'Mecánica en taller y a domicilio, con una foto de un servicio publicado por MyM.',
    gradient: 'linear-gradient(135deg, #111916 0%, #26382D 55%, #D2F36B 140%)',
  },
  {
    slug: 'bxtraining-1',
    name: 'Bxtraining 1',
    rubro: 'Gimnasio',
    city: 'San Clemente',
    tagline: 'Mosaico fotográfico de sala: negro taller, amarillo señal y acero, con fotos.',
    gradient: 'linear-gradient(135deg, #17181A 0%, #8A9199 55%, #FFC300 140%)',
  },
  {
    slug: 'pasteleria-y-panaderia-eluney',
    name: 'Pasteleria y panaderia Eluney',
    rubro: 'Pastelería',
    city: 'Pelarco',
    tagline: 'Historia por pasos: azul eléctrico, lima y línea de tiempo vertical con fotos.',
    gradient: 'linear-gradient(135deg, #0A1A5C 0%, #2251FF 55%, #C6F24E 140%)',
  },
  {
    slug: 'clinica-dental-san-jose',
    name: 'Clínica Dental San José',
    rubro: 'Clínica dental',
    city: 'Molina',
    tagline: 'Neón nocturno clínico: petróleo oscuro, menta con glow y fotos de alto contraste.',
    gradient: 'linear-gradient(135deg, #07141A 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'clinica-prosaluddental',
    name: 'Clínica ProSaludDental',
    rubro: 'Clínica dental',
    city: 'Linares',
    tagline: 'Logístico y puntual: rojo señal, gris flota y hero tipográfico sin foto.',
    gradient: 'linear-gradient(135deg, #8E1B20 0%, #C1272D 55%, #F26722 140%)',
  },
  {
    slug: 'a-toda-maquina-ventas-y-servicios',
    name: 'A Toda Maquina Ventas y Servicios',
    rubro: 'Tienda de máquinas de coser',
    city: 'Linares',
    tagline: 'Ferretero y utilitario: mostaza, verde oscuro y madera, línea de tiempo horizontal con fotos.',
    gradient: 'linear-gradient(135deg, #1E332A 0%, #2E4A3C 55%, #D9A441 140%)',
  },
  {
    slug: 'agrocesped-del-maule',
    name: 'AgroCesped Del Maule',
    rubro: 'Vivero mayorista',
    city: 'San Clemente',
    tagline: 'Tarjetas apiladas al hacer scroll: azul distribución, gris y cian, con fotos.',
    gradient: 'linear-gradient(135deg, #0E2A39 0%, #1F5673 55%, #3CD9EC 140%)',
  },
  {
    slug: 'johnbarber',
    name: 'JohnBarber',
    rubro: 'Barbería',
    city: 'Pencahue',
    tagline: 'Cuadrícula suiza: verde veterinario, crema y ámbar, reglas finas y cartel moderno con fotos.',
    gradient: 'linear-gradient(135deg, #16493A 0%, #2A7F62 55%, #E8A33D 140%)',
  },
  {
    slug: 'ferreteria-don-jack',
    name: 'Ferretería Don Jack',
    rubro: 'Ferretería',
    city: 'Pencahue',
    tagline: 'Carta de la casa: verde campo, tierra y crema, capítulos con numeral romano, puntos guía y carta al vecino.',
    gradient: 'linear-gradient(135deg, #2A3D21 0%, #4C6B3C 55%, #8C6239 140%)',
  },
  {
    slug: 'vulcanizacion-nikimoto',
    name: 'Vulcanizacion nikimoto',
    rubro: 'Taller mecánico',
    city: 'Pelarco',
    tagline: 'Mosaico fotográfico de taller: negro, amarillo señal y acero, franjas de peligro y captions por trabajo.',
    gradient: 'linear-gradient(135deg, #17181A 0%, #3A3D42 55%, #FFC300 140%)',
  },
  {
    slug: 'la-terraza',
    name: 'La Terraza',
    rubro: 'Hamburguesería',
    city: 'Río Claro',
    tagline: 'Directorio funcional: azul noche, arena y terracota, carta con iconos, precios a la derecha y FAQ en bloques, con fotos.',
    gradient: 'linear-gradient(135deg, #121D2E 0%, #1B2A41 55%, #C1663F 140%)',
  },
  {
    slug: 'muebles-a-tu-estilo',
    name: 'muebles a tu estilo',
    rubro: 'Fábrica de muebles',
    city: 'Molina',
    tagline: 'Cartel suizo de taller: verde, crema y ámbar, grilla estricta, reglas finas y tabla de precios de muestra.',
    gradient: 'linear-gradient(135deg, #1D2521 0%, #2A7F62 55%, #E8A33D 140%)',
  },
  {
    slug: 'beauty-love',
    name: 'Beauty Love',
    rubro: 'Salón de manicura y pedicura',
    city: 'Molina',
    tagline: 'Neón nocturno clínico: azul petróleo, menta con glow y blanco roto, fotos de alto contraste.',
    gradient: 'linear-gradient(135deg, #061E25 0%, #0E4C5C 55%, #9FD8CB 140%)',
  },
  {
    slug: 'distribuidora-renato-molina',
    name: 'Distribuidora Renato Molina',
    rubro: 'Mercado',
    city: 'Molina',
    tagline: 'Hero tipográfico sin foto: rojo logística, gris flota y naranja señal, andenes numerados y guía de precios.',
    gradient: 'linear-gradient(135deg, #9A1E23 0%, #C1272D 55%, #F26B1D 140%)',
  },
  {
    slug: 'ius-abogados-linares',
    name: 'IUS Abogados Linares',
    rubro: 'Abogado',
    city: 'Linares',
    tagline: 'Línea de tiempo horizontal: huincha mostaza que cruza la pantalla, verde oscuro y madera, hitos con fotos.',
    gradient: 'linear-gradient(135deg, #1D3128 0%, #2E4A3C 55%, #D9A441 140%)',
  },
  {
    slug: 'defensa-molina-abogados',
    name: 'Defensa Molina Abogados',
    rubro: 'Abogado',
    city: 'Molina',
    tagline: 'Doble columna con sidebar pegajoso: azul pizarra y amarillo lápiz, fichas que explican cada tema, con fotos.',
    gradient: 'linear-gradient(135deg, #1F323E 0%, #2F4858 55%, #F2B705 140%)',
  },
  {
    slug: 'jardin-vivero-carolina',
    name: 'Jardin Vivero Carolina',
    rubro: 'Vivero',
    city: 'Curicó',
    tagline: 'Directorio funcional: azul noche, arena y terracota, lista con fotos, precios a la derecha y FAQ en bloques.',
    gradient: 'linear-gradient(135deg, #1B2A41 0%, #26395A 55%, #C1663F 140%)',
  },
  {
    slug: 'que-barato-lf',
    name: 'QUE BARATO LF',
    rubro: 'Botiquín, escolar y hogar',
    city: 'Talca',
    tagline: 'Catálogo de barrio con cotizador: precio unitario y mayor desde 3 unidades, buscador y tablas por sección.',
    gradient: 'linear-gradient(135deg, #0E3A5C 0%, #1D5E8A 55%, #7FC6E8 140%)',
  },
  {
    slug: 'san-clemente-heladeria',
    name: 'Heladería San Clemente',
    rubro: 'Heladería artesanal',
    city: 'San Clemente',
    tagline: 'Vitrina de sabores: crema, chocolate, frambuesa, pistacho y vainilla, carta por familias con fotos.',
    gradient: 'linear-gradient(135deg, #3B2416 0%, #B01E52 55%, #F2B441 140%)',
  },
  {
    slug: 'estudio-juridico-talca',
    name: 'Convergencia Estudio Jurídico Talca',
    rubro: 'Estudio jurídico',
    city: 'Talca',
    tagline: 'Sereno y editorial: azul noche, dorado y papel, con orientación clara.',
    gradient: 'linear-gradient(135deg, #101A2B 0%, #304768 55%, #D4A64A 140%)',
  },
  {
    slug: 'tricapa-talca-spa',
    name: 'Tricapa Talca',
    rubro: 'Pintura y desabolladura',
    city: 'Talca',
    tagline: 'Taller directo: grafito, amarillo de seguridad y escenas automotrices en SVG.',
    gradient: 'linear-gradient(135deg, #17191B 0%, #586166 55%, #F0B323 140%)',
  },
  {
    slug: 'centro-oftalmologico-nacional',
    name: 'Centro Oftalmológico Nacional',
    rubro: 'Oftalmólogo y óptica',
    city: 'Talca',
    tagline: 'Hero tipográfico con optotipo: azul profundo, cian y blanco clínico, vitrina de armazones con fotos reales.',
    gradient: 'linear-gradient(135deg, #0B2740 0%, #123A5C 55%, #4FB7D9 140%)',
  },
  {
    slug: 'luxe-gym-talca',
    name: 'Luxe Gym',
    rubro: 'Gimnasio',
    city: 'Talca',
    tagline: 'Premium oscuro: carbón y dorado champagne, foto a sangre y reseñas 5.0 con fotos reales.',
    gradient: 'linear-gradient(135deg, #0D0D10 0%, #26262C 55%, #C6A35C 140%)',
  },
  {
    slug: 'kid-mania',
    name: 'Kid Mania',
    rubro: 'Cumpleaños infantiles',
    city: 'Talca',
    tagline: 'Fiesta lista: inflables, animación y decoración temática, con fotos reales del local.',
    gradient: 'linear-gradient(135deg, #2A0F4C 0%, #6D28D9 55%, #D61F7F 140%)',
  },
  {
    slug: 'turismo-las-brujas',
    name: 'Turismo Las Brujas',
    rubro: 'Camping y piscina natural',
    city: 'Colbún',
    tagline: 'Laguna natural, quinchos y arboleda en Colbún, con fotos reales del recinto.',
    gradient: 'linear-gradient(135deg, #0A2E29 0%, #0F766E 60%, #E4DCC6 140%)',
  },
  {
    slug: 'alumrod',
    name: 'Aluminios Alumrod',
    rubro: 'Vidriería y aluminio',
    city: 'Talca',
    tagline: 'Técnico y limpio: acero oscuro, cian vidrio y blanco, con fotos reales del taller.',
    gradient: 'linear-gradient(135deg, #0B151B 0%, #0E7490 140%)',
  },
  {
    slug: 'constructora-valdes',
    name: 'Constructora Valdes',
    rubro: 'Constructora · obras menores',
    city: 'San Clemente',
    tagline: 'Plano de obra: azul marino, dorado mostaza y retícula técnica, con logo real.',
    gradient: 'linear-gradient(135deg, #0D0D33 0%, #D9A441 140%)',
  },
  {
    slug: 'cafeteria-walffies',
    name: 'Cafetería Walffies',
    rubro: 'Cafetería y wafflería',
    city: 'San Clemente',
    tagline: 'Vitrina de wafflería: crema, chocolate y naranjo marca, rejilla de waffle y fotos reales.',
    gradient: 'linear-gradient(135deg, #211208 0%, #3A2415 55%, #E05E1B 140%)',
  },
  {
    slug: 'entre-lomas',
    name: 'Complejo Turístico Entre Lomas',
    rubro: 'Cabañas y turismo',
    city: 'Molina',
    tagline: 'Lodge de cordillera: verde bosque, hueso y ámbar de leña, línea de cerros y fotos reales.',
    gradient: 'linear-gradient(135deg, #122317 0%, #23402B 55%, #D19A3E 140%)',
  },
  {
    slug: 'family-gym-san-clemente',
    name: 'Family Gym',
    rubro: 'Gimnasio · club familiar',
    city: 'San Clemente',
    tagline: 'Club familiar deportivo con fotos y planes reales de su Instagram: violeta nocturno, parallax y valores publicados.',
    gradient: 'linear-gradient(135deg, #150826 0%, #5B21B6 55%, #C4B5FD 140%)',
  },
  {
    slug: 'fonoaudiologa-karen-oyarce',
    name: 'Karen Oyarce',
    rubro: 'Fonoaudiología',
    city: 'Talca',
    tagline: 'Fonoaudióloga en Centro Pichimapu: editorial en teal y menta, retrato real, servicios con precio y agenda por WhatsApp.',
    gradient: 'linear-gradient(135deg, #0E2A28 0%, #0D5F58 55%, #A9E0D2 140%)',
  },
  {
    slug: 'nafi-arquitectura',
    name: 'NAFI Arquitectura',
    rubro: 'Estudio de arquitectura',
    city: 'Talca',
    tagline: 'Editorial de estudio: tinta, papel y cobre, láminas de proyecto apiladas con fotos reales.',
    gradient: 'linear-gradient(135deg, #0D0D0D 0%, #3A3733 55%, #B4643C 140%)',
  },
  {
    slug: 'el-bajon-del-barny',
    name: 'El Bajón del Barny',
    rubro: 'Comida rápida',
    city: 'Talca',
    tagline: 'Neón nocturno de completos: carbón, crema y amarillo señal, con fotos reales del local.',
    gradient: 'linear-gradient(135deg, #13100C 0%, #3A2E14 55%, #FFD23F 140%)',
  },
  {
    slug: 'integravet',
    name: 'Clínica Veterinaria Integravet',
    rubro: 'Clínica veterinaria',
    city: 'Talca',
    tagline: 'La veterinaria 24 h de Talca: verde pino, crema y menta, con su fachada real a sangre.',
    gradient: 'linear-gradient(135deg, #0B3128 0%, #145843 60%, #9FE3B4 140%)',
  },
  {
    slug: 'drivet-animals',
    name: 'DRIVET Animals',
    rubro: 'Hospital veterinario',
    city: 'Talca',
    tagline: 'El hospital del centro: teal, aqua y atención de exóticos, con su fachada real.',
    gradient: 'linear-gradient(135deg, #083238 0%, #0E7C7B 60%, #7FD8CE 140%)',
  },
  {
    slug: 'veterinaria-ramadillas',
    name: 'Veterinaria Ramadillas',
    rubro: 'Clínica y farmacia veterinaria',
    city: 'San Clemente',
    tagline: 'Clínica y farmacia sobre Huamachuco: turquesa, patitas y reseñas reales.',
    gradient: 'linear-gradient(135deg, #0B3B35 0%, #0F7A6D 55%, #35C2AC 140%)',
  },
  {
    slug: 'pepivet',
    name: 'Clínica Veterinaria Pepivet',
    rubro: 'Veterinario',
    city: 'Talca',
    tagline: 'Editorial de barrio: terracota, crema y serif cálida, con la clientela real de 17 Sur.',
    gradient: 'linear-gradient(135deg, #8A3418 0%, #B64F28 60%, #D9A441 140%)',
  },
  {
    slug: 'el-uruguayo',
    name: 'Taller Mecánico El Uruguayo',
    rubro: 'Mecánica a domicilio',
    city: 'San Clemente',
    tagline: 'El taller que llega a donde estés: celeste de ruta, asfalto y señalética, con fotos reales del furgón.',
    gradient: 'linear-gradient(135deg, #0C1824 0%, #1B4A68 55%, #3E9BD0 140%)',
  },
  {
    slug: 'veterinaria-pineiro',
    name: 'Veterinaria Piñeiro',
    rubro: 'Cuidados veterinarios',
    city: 'San Clemente',
    tagline: 'Noche azul, terracota y un pino de guardián: horario real y agenda por WhatsApp.',
    gradient: 'linear-gradient(135deg, #0A1824 0%, #12293B 55%, #D6693B 140%)',
  },
  {
    slug: 'globalauto',
    name: 'GlobalAuto',
    rubro: 'Servicio automotriz',
    city: 'San Clemente',
    tagline: 'Taller moderno negro y naranja: alineación 3D John Bean, specs en mono y fachada real.',
    gradient: 'linear-gradient(135deg, #0E1113 0%, #2A3238 55%, #F26A1B 140%)',
  },
  {
    slug: 'mecanico-juan-vivar',
    name: 'Mecánico Juan Vivar',
    rubro: 'Diagnóstico electrónico',
    city: 'Linares',
    tagline: 'Don Scanner: osciloscopio ámbar sobre negro de taller, terminal de diagnóstico y reseñas reales.',
    gradient: 'linear-gradient(135deg, #0C0F0B 0%, #2A2608 55%, #FFB11F 140%)',
  },
  {
    slug: 'automotriz-gomez',
    name: 'Automotriz Gomez',
    rubro: 'Taller mecánico',
    city: 'Concepción',
    tagline: 'Bandera de meta: carbón y rojo carrera, diagnóstico con fotos y rincón de clásicos.',
    gradient: 'linear-gradient(135deg, #141619 0%, #2A2E35 55%, #D9261D 140%)',
  },
  {
    slug: 's-j-full-car-service',
    name: 'S & J Full Car Service',
    rubro: 'Taller mecánico y serviteca',
    city: 'Talcahuano',
    tagline: 'Serviteca de barrio: azul Mobil, franjas de servicio y pizarra de taller.',
    gradient: 'linear-gradient(135deg, #0C2E63 0%, #1B5ACB 55%, #E2352B 140%)',
  },
  {
    slug: 'hospital-veterinario-talcahuano',
    name: 'Hospital Veterinario Talcahuano',
    rubro: 'Hospital veterinario 24 horas',
    city: 'Talcahuano',
    tagline: 'Índigo y cruz verde: línea de pulso, urgencias 24 h y CTA de llamada.',
    gradient: 'linear-gradient(135deg, #16203E 0%, #1E2A5A 55%, #2E8B6A 140%)',
  },
  {
    slug: 'alcatorce',
    name: 'Alcatorce Restaurant',
    rubro: 'Restaurante panorámico',
    city: 'Concepción',
    tagline: 'Azotea nocturna: tinta profunda, neón lima G14 y el dial del ascensor hasta el piso 14, con fotos reales.',
    gradient: 'linear-gradient(135deg, #0B0E08 0%, #131809 55%, #C6F24E 140%)',
  },
  {
    slug: 'ferreteria-muller',
    name: 'Ferretería Müller',
    rubro: 'Ferretería y materiales',
    city: 'Rancagua',
    tagline: 'Vale de bodega: verde letrero, ámbar y rojo camión, líneas de stock con raya punteada.',
    gradient: 'linear-gradient(135deg, #0D3524 0%, #17573B 55%, #F2B32D 140%)',
  },
  {
    slug: 'ferreteria-avila',
    name: 'Ferretería Ávila',
    rubro: 'Ferretería',
    city: 'Rancagua',
    tagline: 'Letrero pintado a mano: muro blanco, tinta negra y rojo señal, sombra de rótulo y cinta de pasillos.',
    gradient: 'linear-gradient(135deg, #1B1712 0%, #C8102E 60%, #FAF6EC 140%)',
  },
  {
    slug: 'ferreteria-la-esperanza',
    name: 'Ferretería La Esperanza',
    rubro: 'Ferretería y almacén',
    city: 'San Fernando',
    tagline: 'Almacén que abre todos los días: crema, azul puerta y naranja CajaVecina, semana de 7 días y sello giratorio.',
    gradient: 'linear-gradient(135deg, #16386F 0%, #20509E 55%, #E8710A 140%)',
  },
  {
    slug: 'catffeine-cafe',
    name: 'Catffeine Café',
    rubro: 'Cafetería de autor',
    city: 'Copiapó',
    tagline: 'Pizarra oscura con carta de miaus reales, tiza crema, naranja del logo y estela de huellas.',
    gradient: 'linear-gradient(135deg, #191510 0%, #231F19 55%, #F26B21 140%)',
  },
  {
    slug: 'veterinaria-sos-rancagua',
    name: 'Veterinaria S.O.S Rancagua',
    rubro: 'Veterinaria y farmacia',
    city: 'Rancagua',
    tagline: 'Posta nocturna: tinta + lima del mural, boleta de farmacia, urgencias hasta las 2 AM.',
    gradient: 'linear-gradient(135deg, #0C1120 0%, #121B30 55%, #46DC2E 160%)',
  },
  {
    slug: 'patitas-pets-iquique',
    name: 'Patitas Pets Iquique',
    rubro: 'Tienda de mascotas',
    city: 'Iquique',
    tagline: 'Tienda de barrio: crema y verde del logo, mural polaroid y etiquetas colgando del cordel.',
    gradient: 'linear-gradient(135deg, #1D3B0E 0%, #4C8C1E 55%, #FBF5E8 140%)',
  },
  {
    slug: 'centro-veterinario-colchagua',
    name: 'Centro Veterinario Colchagua',
    rubro: 'Veterinaria a domicilio y clínica',
    city: 'San Fernando',
    tagline: 'Ruta de la visita: papel crema del valle, terracota y el «un 7» que repiten sus reseñas.',
    gradient: 'linear-gradient(135deg, #1F2E1A 0%, #23301E 55%, #B8502F 160%)',
  },
  {
    slug: 'luze-vital',
    name: 'Luze Vital',
    rubro: 'Centro de estética integral',
    city: 'Arica',
    tagline: 'Spa de barrio: crema y teal del logo, fotos en arco y la estrella-flor de su marca.',
    gradient: 'linear-gradient(135deg, #0E3235 0%, #17858A 55%, #F7F2E8 140%)',
  },
  {
    slug: 'constructora-avatar',
    name: 'Constructora Avatar',
    rubro: 'Constructora de edificios',
    city: 'Concepción',
    tagline: 'Plano de obra en ciruela: registro numerado de torres reales y una columna de pisos que se apilan.',
    gradient: 'linear-gradient(135deg, #13091F 0%, #1B0F2B 55%, #C77DFF 140%)',
  },
  {
    slug: 'swissvet-talcahuano',
    name: 'SwissVet Talcahuano',
    rubro: 'Veterinaria y peluquería',
    city: 'Talcahuano',
    tagline: 'Ficha clínica suiza: papel crema, rojo del letrero y trama de cruces-pata con pacientes reales.',
    gradient: 'linear-gradient(135deg, #FAF5EA 0%, #F3E7D2 55%, #DE2B1F 140%)',
  },
  {
    slug: 'marco-molina-repuestos',
    name: 'Marco Molina Repuestos',
    rubro: 'Tienda de repuestos automotrices',
    city: 'Linares',
    tagline: 'La marquesina de marcas: navy del local, amarillo del logo y boletas con reseñas reales.',
    gradient: 'linear-gradient(135deg, #0E1B4B 0%, #15265E 55%, #F7C60B 140%)',
  },
  {
    slug: 'freeride-sport-talca',
    name: 'Freeride Sport Talca',
    rubro: 'Tienda de motocicletas',
    city: 'Talca',
    tagline: 'Taller de motos de noche: negro asfalto y tipografía de competición, con ficha real de Maps.',
    gradient: 'linear-gradient(135deg, #0D0D0F 0%, #1C1C21 55%, #F2EFE6 150%)',
  },
  {
    slug: 'lubricantes-sepulveda',
    name: 'Lubricantes Sepúlveda',
    rubro: 'Lubricentro y tienda de repuestos',
    city: 'Talca',
    tagline: 'Vitrina de aceites en verde petróleo: precios publicados, horario real y foto del local.',
    gradient: 'linear-gradient(135deg, #F3EFE4 0%, #52655F 55%, #122E35 140%)',
  },
  {
    slug: 'mila-deco-y-hogar',
    name: 'Mila Deco & Hogar',
    rubro: 'Decoración y artículos para el hogar',
    city: 'Talca',
    tagline: 'Casa de decoración en crema y vino: fichas de productos y despacho a domicilio.',
    gradient: 'linear-gradient(135deg, #FAF5EF 0%, #8E3B4B 120%)',
  },
  {
    slug: 'issa-bella-spa-centro-de-estetica',
    name: 'Issa-bella SpA centro de Estética',
    rubro: 'Centro de estética',
    city: 'Curicó',
    tagline: 'Spa en rosado y crema: servicios, promociones de Instagram y agenda de horas.',
    gradient: 'linear-gradient(135deg, #FBF5F0 0%, #E39DB6 120%)',
  },
  {
    slug: 'constructora-gilaco',
    name: 'Constructora Gilaco',
    rubro: 'Constructora',
    city: 'Talca',
    tagline: 'Plano de obra en gris y negro: remodelaciones, emergencias 24/7 y reseñas reales.',
    gradient: 'linear-gradient(135deg, #F2F0EC 0%, #141416 150%)',
  },
  {
    slug: 'constructora-pehuenche',
    name: 'Constructora Pehuenche',
    rubro: 'Constructora',
    city: 'Talca',
    tagline: 'Papel de plano en verde bosque: obras, confianza y contacto directo.',
    gradient: 'linear-gradient(135deg, #F5F1E8 0%, #1E3A2B 150%)',
  },
  {
    slug: 'yp-construcciones',
    name: 'Y.P Construcciones',
    rubro: 'Construcción y gasfitería',
    city: 'Talca',
    tagline: 'Construcción y gasfitería en tierra y negro: servicios, urgencias y WhatsApp directo.',
    gradient: 'linear-gradient(135deg, #F6F2EA 0%, #1B1610 150%)',
  },
  {
    slug: 'gacitua-producciones-eventos-y-arrie',
    name: 'Gacitúa Producciones y Eventos',
    rubro: 'Banquetería, producción de eventos y arriendo de vajilla',
    city: 'Talca',
    tagline: 'Muestra nueva (ficha de diseno pendiente).',
    gradient: 'linear-gradient(135deg, #F7F3EA 0%, #211E17 150%)',
  },
  {
    slug: 'otel-con-m-caba-as-del-cerro',
    name: 'Cabañas del Cerro',
    rubro: 'Hospedaje',
    city: 'Talca',
    tagline: 'Noche sobre Talca: azul cerro, ámbar ciudad y datos de ruta.',
    gradient: 'linear-gradient(135deg, #0C1230 0%, #141C4A 55%, #F2A93B 150%)',
  },
  {
    slug: 'jard-n-lucerito',
    name: 'Jardín Lucerito',
    rubro: 'Jardín infantil y sala cuna',
    city: 'Talca',
    tagline: 'Papel recortado y sol de crayón: crema, verde y sol.',
    gradient: 'linear-gradient(135deg, #FAF3E3 0%, #F1E5C8 40%, #2E7D5B 140%)',
  },
  {
    slug: 'kine-domicilio-y-consulta-talca',
    name: 'Kine Domicilio y Consulta Talca',
    rubro: 'Kinesiología a domicilio y en consulta',
    city: 'Talca',
    tagline: 'Muestra nueva (ficha de diseno pendiente).',
    gradient: 'linear-gradient(135deg, #F6F8F6 0%, #E9F2EC 150%)',
  },
  {
    slug: 'naru-cocina-japonesa-sushi-talca',
    name: 'NARU Cocina Japonesa & Sushi',
    rubro: 'Cocina japonesa y sushi',
    city: 'Talca',
    tagline: 'Muestra nueva (ficha de diseno pendiente).',
    gradient: 'linear-gradient(135deg, #191210 0%, #F4EEE1 150%)',
  },
  {
    slug: 'yum-express-talca',
    name: 'Yum Express Talca',
    rubro: 'Envíos y encomiendas',
    city: 'Talca',
    tagline: 'Tablero de salidas: navy, azul YUM y amarillo con etiqueta de despacho.',
    gradient: 'linear-gradient(135deg, #0B2B4A 0%, #1B8BD0 70%, #FFC72C 140%)',
  },
  {
    slug: 'camping-y-cabanas-jemaresdagu',
    name: 'Camping y Cabañas Jemaresdagu',
    rubro: 'Camping y cabañas',
    city: 'San Clemente',
    tagline: 'Señalética de parque: crema, madera y búho dorado con tarifas 2026 reales.',
    gradient: 'linear-gradient(135deg, #1E3D2F 0%, #5B3A1E 70%, #C8A24B 140%)',
  },
  {
    slug: 'dinocompletos',
    name: 'Dinocompletos',
    rubro: 'Restaurant de completos',
    city: 'Molina',
    tagline: 'El garage de los completos en Yerbas Buenas: bandera a cuadros, rojo racing y 4,7 en Google.',
    gradient: 'linear-gradient(135deg, #17130F 0%, #7A1418 60%, #F04B40 140%)',
  },
  {
    slug: 'clima-ltda',
    name: 'Clima Ltda.',
    rubro: 'Tienda de aire acondicionado',
    city: 'Talca',
    tagline: 'Ficha técnica de distribuidor Midea y Trane: navy, reglas de plano y tres sucursales.',
    gradient: 'linear-gradient(135deg, #0B2D4E 0%, #14639C 60%, #EFF4F8 140%)',
  },
  {
    slug: 'pasteler-a-mi-caba-a',
    name: 'Pastelería mi cabaña',
    rubro: 'Pastelería',
    city: 'Talca',
    tagline: 'La vitrina de 5 Poniente: repisas con fotos reales, tortas por encargo y crema-frambuesa.',
    gradient: 'linear-gradient(135deg, #3B231B 0%, #B23455 70%, #F3E4CF 140%)',
  },
  {
    slug: 'psic-yaritza-daney-pino-d-az',
    name: 'Psic. Yaritza Daney Pino Díaz',
    rubro: 'Psicóloga clínica',
    city: 'Talca',
    tagline: 'El cuaderno de la consulta: papel verde niebla, serif de bitácora, sesiones con precio real y agenda por Encuadrado.',
    gradient: 'linear-gradient(135deg, #EEF0EA 0%, #2F4A3C 120%)',
  },
  {
    slug: 'aluminios-alumrod',
    name: 'Aluminios Alumrod',
    rubro: 'Aluminios y vidrios',
    city: 'Talca',
    tagline: 'El galpón de franjas rojo-amarillo: planilla de trabajos, condensada industrial y obras reales.',
    gradient: 'linear-gradient(135deg, #1D1B17 0%, #B02218 70%, #F5B800 150%)',
  },
  {
    slug: 'caba-as-cerro-colorado',
    name: 'Cabañas Cerro Colorado',
    rubro: 'Cabañas y alojamiento',
    city: 'Vilches, San Clemente',
    tagline: 'Bitácora de cordillera: curvas de nivel, ficha de alojamiento en mono y guía del entorno del lago Colbún.',
    gradient: 'linear-gradient(135deg, #101E19 0%, #1E3D33 60%, #C25E3A 150%)',
  },
  {
    slug: 'futbolito-las-rastras',
    name: 'Futbolito Las Rastras',
    rubro: 'Complejo deportivo',
    city: 'Talca',
    tagline: 'Canchas sintéticas en la K-55: hero al atardecer con foto real, azul eléctrico + pasto.',
    gradient: 'linear-gradient(135deg, #0A2350 0%, #1E6FF0 60%, #58B23B 140%)',
  },
  {
    slug: 'jaime-acuna-y-cia-ltda',
    name: 'Jaime Acuña y Cía.',
    rubro: 'Contabilidad y auditoría',
    city: 'Talca',
    tagline: 'Estudio sin fotos públicas: tipografía corporate navy y bloques ilustrativos marcados bosquejo.',
    gradient: 'linear-gradient(135deg, #10233A 0%, #2F7FD1 70%, #F3F5F7 140%)',
  },
  {
    slug: 'maestranza-parker',
    name: 'Maestranza Parker',
    rubro: 'Taller de metalurgia',
    city: 'Talca',
    tagline: 'Metalurgia en Ruta 5 Sur: hero de soldador real, grafito + amarillo señalética.',
    gradient: 'linear-gradient(135deg, #17191C 0%, #E4572E 60%, #F2B705 140%)',
  },
  {
    slug: 'kids-art-talca',
    name: 'Kids Art Talca',
    rubro: 'Centro de eventos infantiles',
    city: 'Talca',
    tagline: 'Cumpleaños en Villa Edén: crema de fiesta, confeti y collage en blobs con sus fotos reales.',
    gradient: 'linear-gradient(135deg, #33284A 0%, #C22E78 60%, #FFF3D6 140%)',
  },
  {
    slug: 'protalca-ex-prolimp-talca',
    name: 'Protalca',
    rubro: 'Comercializadora de aseo y hogar',
    city: 'Talca',
    tagline: 'Folleto de ofertas en 27 Sur: rojo folleto, precios de afiche y flyers reales de su Instagram.',
    gradient: 'linear-gradient(135deg, #C41E12 0%, #FFD23F 70%, #FFFDF6 140%)',
  },
  {
    slug: 'estudio-juridico-30-oriente',
    name: 'Estudio Jurídico Talca',
    rubro: 'Abogados y asesoría legal',
    city: 'Talca',
    tagline: 'Carátula de expediente todo-tipográfica: tinta medianoche, latón e índice de secciones.',
    gradient: 'linear-gradient(135deg, #101822 0%, #775126 65%, #F5F0E4 140%)',
  },
  {
    slug: 'envases-y-papeles-talca',
    name: 'Envases y Papeles Talca',
    rubro: 'Servicios',
    city: 'Talca',
    tagline: 'Muestra nueva (ficha de diseno pendiente).',
    gradient: 'linear-gradient(135deg, #3B2C1A 0%, #E7D9BE 150%)',
  },
  {
    slug: 'estudio-chevere',
    name: 'Foto Studio Chevere',
    rubro: 'Servicios',
    city: 'Talca',
    tagline: 'Muestra nueva (ficha de diseno pendiente).',
    gradient: 'linear-gradient(135deg, #2B2119 0%, #F0E3CC 150%)',
  },
  {
    slug: 'ventanas-y-aluminios-inverlum',
    name: 'Ventanas y Aluminios INVERLUM',
    rubro: 'Servicios',
    city: 'Talca',
    tagline: 'Muestra nueva (ficha de diseno pendiente).',
    gradient: 'linear-gradient(135deg, #0D1219 0%, #F2F5F8 150%)',
  },
  {
    slug: 'oass-arriendo-retroexcavadora-y-camiones',
    name: 'OASS · Retroexcavadora y camiones',
    rubro: 'Arriendo de maquinaria',
    city: 'San Clemente',
    tagline: 'Parte de faena: carbón, amarillo máquina, cinta de seguridad y ficha técnica.',
    gradient: 'linear-gradient(135deg, #17140E 0%, #3B331D 55%, #F2C00C 140%)',
  },
]

export const metadata: Metadata = {
  title: 'Demos por rubro — ejemplos de sitios para pymes',
  description:
    'Ejemplos de páginas web para pymes por rubro: escuela de conductores, veterinaria, vivero, óptica, cabañas, ferretería, dental, gasfitería, agencia de publicidad, contador, grúas y vidriería.',
}

export default function DemosIndex() {
  return (
    <div className="min-h-screen bg-cream text-ink">
      <header className="max-w-6xl mx-auto px-5 md:px-8 pt-8 pb-4">
        <Link
          href="/"
          className="font-mono text-xs uppercase tracking-ui text-ink-muted hover:text-ink transition-colors tap-44"
        >
          ← sitiazo.cl
        </Link>
      </header>

      <main className="max-w-6xl mx-auto px-5 md:px-8 pb-24">
        <div className="py-10 md:py-16 max-w-2xl">
          <p className="font-mono text-xs uppercase tracking-ui text-ink-muted mb-4">
            Ejemplos listos para enviar
          </p>
          <h1 className="font-display text-display-md md:text-display-lg font-bold leading-display tracking-display mb-5">
            Demos por rubro
          </h1>
          <p className="text-body text-ink-muted leading-body">
            Mini-sitios de ejemplo, cada uno pensado como un negocio real del
            Maule. Cuando una pyme pregunte «¿me mandas un ejemplo de mi
            rubro?», este es el link.
          </p>
        </div>

        <DemoCatalog demos={DEMOS} blitz={BLITZ} />

        <div className="mt-16 pt-8 border-t border-divider flex flex-col sm:flex-row sm:items-center gap-4 justify-between">
          <p className="text-body-sm text-ink-muted">
            ¿Quieres una así para tu negocio? Escríbenos y la conversamos.
          </p>
          <a
            href={whatsappLink('contacto')}
            target="_blank"
            rel="noopener noreferrer"
            className="shrink-0 font-body text-body-sm font-semibold bg-ink text-cream px-5 py-2.5 transition-transform active:scale-95 tap-44"
          >
            Hablar con {SITE.name} →
          </a>
        </div>
      </main>
    </div>
  )
}
