import { chromium } from 'playwright'
const [slug, w] = process.argv.slice(2)
const b = await chromium.launch()
const p = await (await b.newContext({ viewport: { width: +w, height: 844 }, deviceScaleFactor: 1 })).newPage()
await p.goto(`http://localhost:4800/demos/${slug}/`, { waitUntil: 'networkidle', timeout: 60000 })
await p.waitForTimeout(2500)
await p.screenshot({ path: `/home/ubuntu/work/qa/${slug}-${w}-top.png` })
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight * 0.35))
await p.waitForTimeout(1500)
await p.screenshot({ path: `/home/ubuntu/work/qa/${slug}-${w}-mid.png` })
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
await p.waitForTimeout(1800)
await p.screenshot({ path: `/home/ubuntu/work/qa/${slug}-${w}-end.png` })
await b.close()
